name: Check changed adapters

on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run test
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
          GITHUB_REF: ${{ env.GITHUB_REF }}
          GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
